name: build

on: [push]

jobs:
  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
     - name: Update git
        run: apt update && DEBIAN_FRONTEND=noninteractive TZ="Europe/Amsterdam" apt install -y git build-essential

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Install dependencies in order to be able to compile the project.
      - name: Install openFrameworks dependencies
        run: sudo bash ./openFrameworks/scripts/linux/ubuntu/install_dependencies.sh -y

      # Downloading additional libs for ofx
      - name: Download openFrameworks libs
        run: bash ./openFrameworks/scripts/linux/download_libs.sh

      # Build openFrameworks
      - name: Building openFrameworks
        run: bash ./openFrameworks/scripts/linux/compileOF.sh

      - name: Copying library
        working-directory: ${{github.workspace}}
        run: cp -rf ./ofxOfelia ./openFrameworks/addons/ofxOfelia

      # Building the project
      - name: Building Ofelia
        working-directory: ${{github.workspace}}/openFrameworks/addons/ofxOfelia
        run: |
          echo "test"

      # Upload executable binaries to GitHub
      #- name: Uploading artifacts
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: Linux Artifacts
      #    path: ./iva/ivaApp/bin/

  build-mac:
    # the build server's operating system
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Downloading additional libs for openFrameworks
      - name: Download openFrameworks libs
        run: bash ./openFrameworks/scripts/osx/download_libs.sh

      - name: Install project generator
        run: |
          cd ./openFrameworks/
          echo "Downloading projectGenerator from ci server"
          wget http://ci.openframeworks.cc/projectGenerator/projectGenerator-osx.zip
          unzip projectGenerator-osx.zip
          rm projectGenerator-osx.zip

      - name: Create project files for xcode
        run: |
          ./openFrameworks/projectGenerator-osx/projectGenerator.app/Contents/Resources/app/app/projectGenerator -o"./openFrameworks" -p"osx" ./iva/ivaApp

      - name: Copying library
        working-directory: ${{github.workspace}}
        run: cp -rf ./ofxOfelia ./openFrameworks/addons/ofxOfelia

      # Building the project
      - name: Building Ofelia
        working-directory: ${{github.workspace}}/openFrameworks/addons/ofxOfelia
        run: |
          echo "test"

      # Upload executable binaries to GitHub
      #- name: Uploading artifacts
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: Mac Os Artifacts
      #    path: ./iva/ivaApp/bin/