name: build

on: [push]

jobs:
  build-debian:
    runs-on: ubuntu-latest

    steps:
      - name: Install base dependencies
        run: sudo apt update && sudo DEBIAN_FRONTEND=noninteractive TZ="Europe/Amsterdam" apt install -y git build-essential pkg-config wget rsync libassimp-dev

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Downloading additional libs for openFrameworks
      - name: Installing dependencies
        run: ./install_libs.sh

      # Building the project
      - name: Building Ofelia
        run: ./build.sh

      # Upload executable binaries to GitHub
      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plugdata-ofelia-macos
          path: ./ofelia

  build-mac:
    # the build server's operating system
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Downloading additional libs for openFrameworks
      - name: Installing dependencies
        run: ./install_libs.sh

      # Building the project
      - name: Building Ofelia
        run: ./build.sh

      # Upload executable binaries to GitHub
      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plugdata-ofelia-macos
          path: ./ofelia